### PR TITLE
smd-ver

### PR DESCRIPTION
**Pull request by qelloman**
#4 through-hole to SMD

XBEE and Pi connectors are changed to smd connectors.

### CODE REVIEW

**Comment by hrldcpr** [comment]
Thanks @qelloman! A couple questions:
- What is this via? It seems like it doesn't do anything.
  image
- Are you using the same SparkFun settings we've been using? You should run [this SCR script](https://github.com/sparkfun/SparkFun_Eagle_Settings/blob/master/scr/eagle.scr) after you open the board, and then use [this DRU file](https://github.com/sparkfun/SparkFun_Eagle_Settings/blob/master/dru/SparkFun-2-layer-STANDARD.dru) to do the DRC checks. Currently there are a lot of DRC violations, I doubt any are serious but it's probably easier to work with the board if we fix all of them.

Other than that, the SMD headers look really cool, and it's nice to know that they are cheaper and easier for companies to assemble for us.

**Comment by qelloman** [comment]
@hrldcpr Hi, I just fixed most errors by using sparkfun settings.
It still has angle errors but they are known as bug. Also, it will be overlapped by other top and bottom layer so don't worry.
This new board still has a via like above, because they share 3.3V VDD by bottom plate.
Please let me know if you see something wrong.

**Comment by williamcodes** [comment]
Wow, I need to watch the comments before I go sending files to manufacturers. Good catch, @hrldcpr! Also I need to make sure we have an updated BOM. Do we have an updated BOM? Should we check the BOM spreadsheet into version control so it's easier to match versions of the brd to versions of the BOM?

**Comment by hrldcpr** [comment]
Thanks for the updates @qelloman! I hadn't noticed you switched the ground/power planes, now that via makes sense. I like how the board is smaller now.

I'll merge and then fix the angle errors (you just have to be careful not to make weird little mini-traces, not sure where they come from…)

@williamcodes yeah go ahead and add the BOM to the repo, makes sense

**Pull request merged**
